name: google_static_maps_controller
description: The package provides simple and declarative access to the Google Static Maps service.
repository: https://github.com/gonuit/flutter_google_static_maps
homepage: https://github.com/gonuit/flutter_google_static_maps
issue_tracker: https://github.com/gonuit/flutter_google_static_maps/issues

version: 1.1.0

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
